/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#d0c6ab",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "outline": "#999077",
        "outline-variant": "#4d4732",
        "surface-tint": "#e9c400",
        "primary": "#fff6df",
        "on-primary": "#3a3000",
        "primary-container": "#ffd700",
        "on-primary-container": "#705e00",
        "inverse-primary": "#705d00",
        "secondary": "#ffb3b1",
        "on-secondary": "#680011",
        "secondary-container": "#ad0224",
        "on-secondary-container": "#ffb8b5",
        "tertiary": "#f3f6ff",
        "on-tertiary": "#253142",
        "tertiary-container": "#cedaf1",
        "on-tertiary-container": "#545f73",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffe16d",
        "primary-fixed-dim": "#e9c400",
        "on-primary-fixed": "#221b00",
        "on-primary-fixed-variant": "#544600",
        "secondary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#ffb3b1",
        "on-secondary-fixed": "#410007",
        "on-secondary-fixed-variant": "#92001c",
        "tertiary-fixed": "#d7e3fa",
        "tertiary-fixed-dim": "#bbc7dd",
        "on-tertiary-fixed": "#101c2c",
        "on-tertiary-fixed-variant": "#3c475a",
        "background": "#131313",
        "on-background": "#e5e2e1"
      },
      spacing: {
        "spotlight-padding": "120px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "container-max": "1200px",
        "unit": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "display-xl": ["Anton", "sans-serif"],
        "headline-lg": ["Anton", "sans-serif"],
        "headline-lg-mobile": ["Anton", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "88px", letterSpacing: "0.02em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
